Initial pass of workbox-cli conversion
GoogleChrome/workbox pull request #2537
Opened 2020-06-11 07:18 UTC by philkrie

R: @jeffposnick @philipwalton

*begins* to fix #2476

Initial pass. I'm able to get it to run, but tests aren't passing. Please take a look when you have a chance and let me know if I'm on the right track, i'm not very experienced w/ Typescript and there are some a few hacky solutions for now (search for //FIX).

package.json contains devDependencies for the types of some npm packages, which if I recall from the tests shouldn't be used. I also was messing around w/ module/target configs in tsconfig: since this is not imported as a module like most of the workbox packages, I wasn't sure if the default tsconfig should be changed.

In terms of tests, when running `gulp test --package="workbox-cli" --fix` I get almost entirely errors like this: 

`48) [workbox-cli] lib/run-wizard.js should write the configuration to the expected location based on the answers provided:
TypeError: runWizard is not a function
      at Context.<anonymous> (test/workbox-cli/node/lib/run-wizard.js:35:11)
      at processImmediate (internal/timers.js:439:21)
      at process.topLevelDomainCallback (domain.js:130:23)`

It doesn't seem to like how I exported functions in my typescript, but I'm unsure what the solution is.

2020-06-12 19:46 UTC, jeffposnick commented
Hey @philkrie! I'll leave some inline feedback, but in the meantime, could you rebase this so that the PR goes against the `v6` branch instead of `master`?

2020-06-12 21:01 UTC, jeffposnick requested changes

2020-06-12 21:01 UTC, jeffposnick commented on packages/workbox-cli/src/app.ts
> +        await (workboxBuild as any)[command](config); //FIX this is dubious
If you limit `command` to 'generateSW' or `'injectManifest'` as per the earlier comment, you shouldn't have to cast `workboxBuild` to `any`.

You might still need to massage `config` a bit since the two take a different set of options, though.

2020-06-12 21:01 UTC, jeffposnick commented on packages/workbox-cli/src/app.ts
> +          .map((filePath: string) => `  • ${filePath}`)
`: string` shouldn't be necessary; TypeScript can infer it based on the type of `filePaths`.

2020-06-12 21:01 UTC, jeffposnick commented on packages/workbox-cli/src/app.ts
> +  command: string;
You can limit the possible values via:

```
command: 'generateSW'|'injectManifest';
```

2020-06-12 21:01 UTC, jeffposnick commented on packages/workbox-cli/package.json
> +    "@types/meow": "5.0.0",
I haven't checked all of these, but `meow`, at least, publishes its own types alongside the official module. You shouldn't have to import unofficial types from DefinitelyTyped.

https://github.com/sindresorhus/meow/blob/master/index.d.ts

2020-06-12 21:01 UTC, jeffposnick commented on packages/workbox-cli/src/bin.ts
> +  const params: meow.Result<any> = meow(helpText);
You can do

```
export interface SupportedFlags extends meow.AnyFlags {
  debug: meow.BooleanFlag;
  injectManifest: meow.BooleanFlag;
  watch: meow.BooleanFlag;
}
```

(those are the three supported flags) and then write `meow.Result<SupportedFlags>` instead of `meow.Result<any>`.

If you export the interface here, you can then import it in `app.ts` and reuse it.

2020-06-12 21:01 UTC, jeffposnick commented on packages/workbox-cli/src/app.ts
> +export const app = async (params: meow.Result<any>) => {
See later comment—this can be `meow.Result<SupportedFlags>`.

2020-06-12 21:01 UTC, jeffposnick commented on packages/workbox-cli/src/lib/cleanup-stack-trace.ts
> +  const frames = error?.stack?.split(`\n`);
In our use case, if `error.stack` isn't set, it's probably cleanest to just return early.

Adding this to the top of the function will allow you to drop all of the `?` characters, since if you get that far, `error.stack` was set.

```
if (!error.stack) {
  return '';
}
```

2020-06-12 21:01 UTC, jeffposnick commented on packages/workbox-cli/src/lib/cleanup-stack-trace.ts
> +  let startFrame = -1;
You should be able to say:

```
let startFrame: number;
```

2020-06-12 21:01 UTC, jeffposnick commented on packages/workbox-cli/src/lib/cleanup-stack-trace.ts
> +    if (startFrame === -1 && frame.includes(`    at `)) {
Assuming you've set the type of `startFrame` to `number` as per the previous suggestion, this can be

```
if (startFrame === undefined && ...)
```

(I would rather keep the logic as-is instead of using `-1` as a "magic" value, although it's probably equivalent.)

2020-06-12 21:01 UTC, jeffposnick commented on packages/workbox-cli/src/lib/questions/ask-config-location.ts
> +function askQuestion(): Promise<Answers> {
I think you can leave out the `: Promise<Answers>` here, as the type is inferred by the only return value.

2020-06-12 21:01 UTC, jeffposnick commented on packages/workbox-cli/src/lib/questions/ask-extensions-to-cache.ts
> +async function getAllFileExtensions(globDirectory: string): Promise<Array<string>> {
You can leave out the `: Promise<Array<string>>` here, as the type is inferred by the `return` value.

2020-06-12 21:01 UTC, jeffposnick commented on packages/workbox-cli/src/lib/questions/ask-extensions-to-cache.ts
> +async function askQuestion(globDirectory: string): Promise<Answers> {
Again, you should be able to leave out this `return` type.

2020-06-12 21:01 UTC, jeffposnick commented on packages/workbox-cli/src/lib/questions/ask-root-of-web-app.ts
> +async function getSubdirectories(): Promise<Array<string>> {
You can remove the `return` type definition.

2020-06-12 21:01 UTC, jeffposnick commented on packages/workbox-cli/src/lib/questions/ask-root-of-web-app.ts
> +async function askQuestion(): Promise<Answers> {
Ditto on removing the `return` type.

2020-06-12 21:01 UTC, jeffposnick commented on packages/workbox-cli/src/lib/questions/ask-root-of-web-app.ts
> +        new Separator() as unknown as string, //FIX This is kinda funky, but was triggering type error
Try `new Separator().toString()`, as per https://github.com/SBoudrias/Inquirer.js/blob/039a55c7ec04d95887bdeb9b164cc634f26beb57/packages/inquirer/lib/objects/separator.js#L22-L24

The string conversion was previously implicit.

2020-06-12 21:01 UTC, jeffposnick commented on packages/workbox-cli/src/lib/questions/ask-sw-dest.ts
> +function askQuestion(defaultDir: string): Promise<Answers> {
You can drop the `return` type.

2020-06-12 21:01 UTC, jeffposnick commented on packages/workbox-cli/src/lib/questions/ask-sw-src.ts
> +function askQuestion(): Promise<Answers> {
You can drop the `return` type.

2020-06-12 21:01 UTC, jeffposnick commented on packages/workbox-cli/src/lib/read-config.ts
> +export function readConfig(configFile: string):any{require(configFile)};
This should be

```
export function readConfig(configFile: string) {
  return require(configFile);
};
```

2020-06-12 21:01 UTC, jeffposnick commented on packages/workbox-cli/tsconfig.json
> +{
I am not 100% sure about the values to use here. If you get caught up, @philipwalton might be able to provide some guidance.

2020-06-16 23:46 UTC, philkrie commented on packages/workbox-cli/src/lib/cleanup-stack-trace.ts
> +  let startFrame = -1;
This throws an error on line 29 that the variable is used before assignment. How about:

`let startFrame: number; | undefined`

2020-06-16 23:52 UTC, philkrie commented on packages/workbox-cli/src/lib/questions/ask-extensions-to-cache.ts
> +async function getAllFileExtensions(globDirectory: string): Promise<Array<string>> {
It doesn't appear to be: leaving this out results in `const subdirectories` being unknown on line 45.

2020-06-16 23:55 UTC, philkrie commented on packages/workbox-cli/src/lib/questions/ask-root-of-web-app.ts
> +async function getSubdirectories(): Promise<Array<string>> {
the inferred type is Promise<unknown>, which causes line 45 `const subdirectories`  to be typed as unknown. Is there a better way to resolve this?

2020-06-17 01:22 UTC, philkrie commented on packages/workbox-cli/src/app.ts
> +        await (workboxBuild as any)[command](config); //FIX this is dubious
I was able to use `GenerateSWConfig & InjectManifestConfig;`

2020-06-17 01:25 UTC, philkrie commented
Tests are still failing, but I think those need to be rewritten. For example, currently I'm getting errors due to `const app = require(MODULE_PATH);` not being a function. I have to unpack it a la `const {app} = require(MODULE_PATH);` Should I rewrite the tests, or is the issue in how I'm using export?

2020-06-22 18:44 UTC, jeffposnick commented
I can take a look at the tests for you. I think it's going to require (hah!) a bit of changing the underlying module loading plumbing.

2020-07-07 21:05 UTC, jeffposnick commented
I changed the build to run anything with a `packageType: 'node_ts'` field in its `package.json` through `tsc`. That, plus massaging some of the tests to use named exports instead of `default` and I think we're ready to go with this PR!

The one messy thing is that your original PR differs a bit from the `v6` branch's `demos/` directory, so this PR includes some of those changes as well. At this point, I think the easiest thing to do will be to merge and then sanity check the `demos/` later. (When we switched the base from `master` to `v6` that led to the confusion.)

2020-07-08 15:11 UTC, jeffposnick approved these changes

2020-07-08 15:11 UTC, merged