Migrate workbox-build to TypeScript
GoogleChrome/workbox pull request #2867
Opened 2021-06-15 15:39 UTC by jeffposnick

R: @tropicadri

Fixes #2806, fixes #2477

There's obviously a _lot_ going on in this PR. Sorry!

At a high level, this migrates `workbox-build` to TypeScript. (Following this PR, only `workbox-webpack-plugin` and `workbox-sw` are written in JavaScript.)

The goal was to preserve functionality during this migration, and not require a major semver bump. The biggest change under the hood is swapping out `@hapi/joi` option validation for a two-part system that generates JSON schema based on our TypeScript definitions at build time, and then uses https://ajv.js.org/ to validate at runtime against that schema. `@hapi/joi` is a bit more sophisticated in terms of complex runtime validation (e.g. ensuring that if one option is set, another option needs to also be set, making options mutually exclusive, etc.) so some of those relationships needed to be expressed at runtime via custom functions, meaning that the generated JSON schema are not 100% the source of truth.

Many of the test changes across all the packages reflect the fact that validation now throws slightly different errors due to the above mentioned change.

There are other small changes sprinkled throughout this PR as well, based on things that I found necessary while working with the additional TypeScript code. Please flag anything that looks amiss!

2021-06-16 03:10 UTC, tropicadri requested changes
There are several linting errors and I added a couple of suggestions.

2021-06-16 03:10 UTC, tropicadri commented on packages/workbox-build/src/lib/get-file-details.ts
> +  Copyright 2018 Google LLC
```suggestion
  Copyright 2021 Google LLC
```

2021-06-16 03:10 UTC, tropicadri commented on test/workbox-build/node/generate-sw.js
> +    it(`should reject when 'navigationPreload' is true and 'runtimeCaching' is invalid`, async function() {
```suggestion
    it(`should reject when 'navigationPreload' is true and 'runtimeCaching' is undefined`, async function() {
```

2021-06-16 03:10 UTC, tropicadri commented on packages/workbox-build/src/lib/additional-manifest-entries-transform.ts
>      const warnings = [];
```suggestion
    const warnings : Array<string> = [];
```

2021-06-16 03:10 UTC, tropicadri commented on packages/workbox-build/src/lib/additional-manifest-entries-transform.ts
>      const stringEntries = new Set();
```suggestion
    const stringEntries = new Set<string>();
```

2021-06-16 03:10 UTC, tropicadri commented on packages/workbox-build/src/lib/cdn-utils.ts
> +  Copyright 2018 Google LLC
```suggestion
  Copyright 2021 Google LLC
```

2021-06-16 03:10 UTC, tropicadri commented on packages/workbox-build/src/lib/get-file-manifest-entries.ts
> +  Copyright 2018 Google LLC
```suggestion
  Copyright 2021 Google LLC
```

2021-06-16 03:10 UTC, tropicadri commented on packages/workbox-build/src/lib/stringify-without-comments.ts
> +  Copyright 2018 Google LLC
```suggestion
  Copyright 2021 Google LLC
```

2021-06-16 03:10 UTC, tropicadri commented on packages/workbox-build/src/lib/validate-options.ts
> +  Copyright 2019 Google LLC
```suggestion
  Copyright 2021 Google LLC
```

2021-06-16 14:27 UTC, jeffposnick commented
Thanks! Regarding the linting errors, I'm not going to be able to resolve the three instances of `Parsing error: Cannot read property 'map' of undefined` in this PR. As per https://stackoverflow.com/a/64626605/385997,  we're going to have to upgrade our TypeScript eslint dependencies to resolve them, and that's a larger effort being done in the other PR that you're working on.

The other errors should be resolved now, though.

2021-06-16 23:53 UTC, tropicadri approved these changes
Sorry there was a typo in one of my previous suggestions, I added the fix.

Ack on the map undefined issue.

LGTM

2021-06-16 23:53 UTC, tropicadri commented on packages/workbox-build/src/lib/additional-manifest-entries-transform.ts
> +    const warnings : Array<string> = [];
```suggestion
    const warnings: Array<string> = [];
```

2021-06-17 13:41 UTC, merged

2021-07-16 23:24 UTC, alsayedzomrawi commented
[1394web.pdf](https://github.com/GoogleChrome/workbox/files/6833794/1394web.pdf)