upgrade to tslin dependencies from 2.30 to 4.28
GoogleChrome/workbox pull request #2885
Opened 2021-07-07 22:58 UTC by tropicadri

Fixes #2602 

Many of the errors that are fixed are about [ban types](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/ban-types.md) for the use of any, object, or {}. I gave the ones that I could proper types, but some of them are part of our external interface so, I'm ignoring them for now.

Other fixes are in string literals, that only take string or number as types, and  adding return types to functions.

2021-07-08 20:53 UTC, jeffposnick requested changes
Thanks so much for all the work on this! There are just a small number of comments.

2021-07-08 20:53 UTC, jeffposnick commented on packages/workbox-build/src/inject-manifest.ts
> +  ${options.injectionPoint ? options.injectionPoint : ''}`);
I think this could just be `injectionPoint`, since you've previously created that variable with this value.

2021-07-08 20:53 UTC, jeffposnick commented on packages/workbox-core/src/models/messages/messages.ts
> +  [key: string]: string | number;
Do you know which named error function returns a `number`? I had thought all of them returned `string`, and if one doesn't, that might be a bug.

2021-07-08 20:53 UTC, jeffposnick commented on packages/workbox-window/src/Workbox.ts
> +  async messageSW(data: Record<string, unknown>): Promise<any> {
Just wanted to check that this transition from `object` to `Record<string, unknown>` is backwards-compatible.

2021-07-08 20:53 UTC, jeffposnick commented on packages/workbox-strategies/src/StrategyHandler.ts
> +      if (err instanceof Error) {
It looks like the indentation is off here.

2021-07-10 00:10 UTC, tropicadri reviewed
Thank you for you review, this was huge!

2021-07-10 00:10 UTC, tropicadri commented on packages/workbox-core/src/models/messages/messages.ts
> +  [key: string]: string | number;
these are the types of the objects that come in params, for 'range-not-satisfiable' start and end are numbers.

2021-07-10 00:10 UTC, tropicadri commented on packages/workbox-window/src/Workbox.ts
> +  async messageSW(data: Record<string, unknown>): Promise<any> {
ah good catch, I was testing some changes. Not 100% sure, so won't change right now :)

2021-07-12 17:50 UTC, jeffposnick commented on packages/workbox-core/src/models/messages/messages.ts
> +  [key: string]: string | number;
Gotcha.

2021-07-12 17:51 UTC, jeffposnick approved these changes
Thanks again!

2021-07-12 17:51 UTC, merged